### ISSUE TITLE
Field level resolver makes the field disappear from TS typegen

### ISSUE THREAD

**Issue by halotest** [graphql-nexus/nexus#1006]
Hi. I want to store 1-many relation in an array which contains ids to related objects. `orders: [123, 456, 789]`
And then I want that field level resolver to grab related objects but as soon as i add resolver function the field disappears and TS raises an error saying field does not exist on type. Relevant image:
<img width="421" alt="Снимок экрана 2021-10-29 в 11 26 24" src="https://user-images.githubusercontent.com/8064916/139377667-5207b714-9266-4c26-8627-e8eefcce1821.png">
For example having only type: `type: list("Order")` does not remove the field from TS typegen but as soon as resolve func is added, the field is gone.

What's the problem here? Am i misunderstanding something?

**Comment by jcpage** [comment]
Thanks @tgriesser, I think I understand the intent better now.  For the the original issue your helper might cover it - in my case I think I just misunderstood the issue I was having, which is that I need to better define my source types externally when graphql doesn't match the db.

Just throwing out an idea - it might interesting if you were able to add something to help infer source fields in the same definition... like another function that only defined it for the source (naming convention totally made up and could be improved, but hopefully you get my idea).  Basically the feature that this would implement is automatically including fields in the generated source type that you DON'T want in the generated graphql schema:

```
t.sourceField('imageKey', {
  type: 'String'
})
t.string('imageUrl', {
  resolve: (src) { return `https:/cdn.path/${src.imageKey}` }
})
```

Or maybe you could have an option that basically excluded it from the graphql schema so it's only in the source type (though this may be somewhat confusing since the point of nexus is generating schema so skipping that part seems odd... though it could potentially work with your suggestion 'sourceType' so you effectively can tell it to include it in the schema, the interface, or both)

```
t.string('imageKey', {
  sourceOnly: true
})
t.string('imageUrl', {
  resolve: (src) { return `https:/cdn.path/${src.imageKey}` }
})
```
I suppose this could easily be done with a plugin (especially the first suggestion) - maybe I'll play around with it ;)

**Comment by jcpage** [comment]
Re: my previous comment - from the start I was surprised Nexus couldn't just use the Prisma types that were generated and specified in sourceTypes in makeSchema.  I found if I changed it to explicitly reference the generated ts instead of the module it works (by just defining the source type to be "MyType: prisma.MyType"

```
        //module: '@prisma/client',
       module: '.prisma/client/index.d.ts',
```
I guess the previous suggestion might still be useful if people don't want to use Prisma types or aren't using Prisma at all...

**Comment by nenadfilipovic** [comment]
@jcpage this is enough `module: '.prisma/client',`

**Comment by tgriesser** [comment]
> For the the original issue your helper might cover it - in my case I think I just misunderstood the issue I was having, which is that I need to better define my source types externally when graphql doesn't match the db.

Yeah, the recommended way to do that inline currently is by configuring the `sourceType` for the type:

```ts
export const User = objectType({
  name: 'User',
  definition(t) {
  	t.string('imageUrl', {
     resolve: (src) => { return `https://cdn.path/${src.imageKey}` }
    })
  },
  sourceType: '{ imageKey: string }'
})
```

```ts
export interface UserShape {
  imageKey: string
}

objectType({
  name: 'User',
  definition(t) {
  	t.string('imageUrl', {
     resolve: (src) => { return `https://cdn.path/${src.imageKey}` }
    })
  },
  sourceType: {
    module: __filename,
    export: 'UserShape'
  }
})
```

**Comment by halotest** [comment]
Another problem i'm facing regarding this topic and looking for helps is, i have a global interface which DB all objects implement: 

```js
export interface INode {
	_id: ObjectId
	object_type: string
}

export const Node = interfaceType({
	name: "Node",
	sourceType: {
		module: __filename,
		export: "INode",
	},
	// @ts-ignore
	resolveType(data) {
		return data.object_type
	},
	definition(t) {
		t.nonNull.id("id", {
			resolve(data) {
				return data._id.toString()
			},
		})
		t.nonNull.id("_id", {
			resolve: ({ _id }) => _id.toString(),
		})
		t.nonNull.date("createdAt")
		t.nonNull.date("updatedAt")
		t.date("deletedAt")
		t.nonNull.string("object_type")
		t.string("code")
	},
})

```

and since i'm using mongo, i want to map its default "_id" to "id" field in schema. The problem here is, do i really have to keep both "id" and "_id" in the interface? I don't want both to appear in my schema and be queryable, i just want the "id", but when i delete the "_id" field from the interface and trying to resolve some field from an object that implements the "node" interface like, i'm obviously getting an error that "_id" does not exist but i need a type for that because the _id is what mongo sends back, this forces me to keep both _id and id in my schema, thus making both queryable.  having source type with that _id field does not help either, objects that implement the node don't see it. Is there a way around that to generate just TS for a field but don't put the field to schema?

**Comment by tgriesser** [comment]
Opened #1106 to help with this

**Comment by lmanerich** [comment]
hi @tgriesser this still doesn't solve how to link to another generated type

`
objectType({
    name: 'Post',
    definition(t) {
        t.id('id');
        t.string('label', {
            resolve: PostResolver.label,
            sourceType: 'string',
        });
        t.field('user', {
            type: 'User',
            resolve: PostResolver.user,
            sourceType: 'User',
        });
    },
}
`

Ends up generating:

`
export interface NexusGenObjects {
  Query: {};
  Post: { // root type
    id?: string | null; // ID
    label: string
    user: User ///// NOT DEFINED
  }
`

As a workaround it is possible to declare the type as

`
sourceType: "NexusGenRootTypes['User']",
`

**Comment by VincentGillot** [comment]
Is there any news on this?
Because if I use:
`  sourceType: {
    module: __filename,
    export: 'UserShape'
  }`
The type is correctly imported in the generated types file but since I use this file in the front-end I don't have access to the import.

**Comment by georgekrax** [comment]
@VincentGillot Unfortunately, there has not been any update on this issue, and I am not aware wether they continue to maintain the Nexus project yet.
