### ISSUE TITLE
Is it possible to extract types from objectType 

### ISSUE THREAD

**Issue by cevr** [graphql-nexus/nexus#558]
Is it possible to extract types from `objectType` ?

use case:

My schema is a graphql layer behind non-graphql services, so in the resolvers, I call these services to retrieve the data.

It would make it incredibly simple if I could do something like this:

```
export const test = objectType({
  name: 'Test',
  definition(t) {
    t.id('id', { nullable: false });
    t.string('name', { nullable: false });
  },
});

type Test = extractType<typeof test>
```
Is this currently possible?

**Comment by Sytten** [comment]
Somewhat similar to issue https://github.com/graphql-nexus/schema/issues/560 except one is generating code and the other is requesting an extract method.
AFAIK it would not be possible to extract the type due to the structure that nexus uses (definition `t` vs an object with keys ala prisma). So the best effort would be to generate types at the same time as the rest. Like I said in the other issues, I think this is already possible using plugin but I am not sure.

**Comment by cevr** [comment]
Are there plans on adding support for this? It's very useful for graphql gateways.

**Comment by Sytten** [comment]
Correct me if I am wrong @tgriesser but I think that could be user land and most likely a community plugin, feel free to give it a shot @cevr!

**Comment by cevr** [comment]
@Sytten That's interesting. A plugin as in like the plugins Nexus offers? I will investigate but it's not clear to me how to create a plugin that allows for type extractions 😭

It seems like this would be easier if nexus had an api like this:

```ts
definition: (t, define) => define(t.id("id"), t.int("count"))
```
Then printing/extraction would be pretty straightforward
