### ISSUE TITLE
Optional fields for typescript generated types with makeSchema

### ISSUE THREAD

**Issue by lhguerra** [graphql-nexus/nexus#903]
I'm struggling with a type that has an optional field, and I want to treat it as optional in ts but using the generated type.

I declare my graphql type like this:
```
export const MyAwesomeQuery = extendType({
  type: 'City',
  definition(t) {
    t.list.nullable.field('streets', {
      type: 'Street',
      ...
    })
  },
})
```

And makeSchema generates a type like this:
```
City: {
    streets: Array<NexusGenRootTypes['Street'] | null> | null;
  }
```

But for my business logic I need streets to be optional, so the ts type should look like this:
```
City: {
    streets?: Array<NexusGenRootTypes['Street']>;
  }
```

Is that possible with makeSchema? Sorry if I'm asking in the wrong place (:

**Comment by chrishoermann** [comment]
I don't know if makeSchema is capable of doing this but why don't you just use the custom type from your example for your business logic? You already reference the base type via `NexusGenRootTypes` so if this type changes your custom type also changes accordingly.

**Comment by lhguerra** [comment]
I don't know if I understand what you mean by using the custom type.

**Comment by chrishoermann** [comment]
with custom type I mean that you can define it yourself like 

```typescript
interface City {
  streets?: Array<NexusGenRootTypes["Street"]>;
}
```
and use this type/interface in your logic instead of the generated one. 
The thing is that this only works in situations where you have control over your typing - e.g. I use this kind of type generation in my testing environment.

But do I assume right that you want `streets ` to be either `undefined` or an `array containing street names` ?

then first you can make streets nonNullable with nexus

```typescript
export const MyAwesomeQuery = extendType({
  type: 'City',
  definition(t) {
    t.list.nullable.field('streets', {
      type: nonNull('Street'), // use nonNull from nexus
      ...
    })
  },
})
```

this should generate a ts type like this 

```typescript
City: {
    streets: Array<NexusGenRootTypes['Street']> | null;
  }
```

Now the conception of graphql comes into play: `null` is the `undefined` or `None` of GraphQL
If you want your list to be optional it will by definition be either `null` or the actual `list with street types`.  
and because of the fact that nexus generates graphql you can't get rid of `nulls` with makeSchema.

you can read a bit about nullability in nexus and graphql here: https://nexusjs.org/docs/guides/nullability

So if you want to use the generated type, I think you have to deal with null values in your logic.

Sidenote: There is a guide on how to deal with null values in prisma: https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined
maybe this also can shed a bit more light onto the topic

I hope this explanation helps.

**Comment by Sytten** [comment]
@lhguerra I think you just need to switch the nullable to the other side of the list.
```typescript
export const MyAwesomeQuery = extendType({
  type: 'City',
  definition(t) {
    t.nullable.list.field('streets', {
      type: 'Street',
      ...
    })
  },
})
```
`I want a nullable list of non-nullable streets` vs `I want a non-nullable list of nullable streets`
Let me know if that is not working.
