### ISSUE TITLE
Can someone help me with Nexus JS when using Relationships?

### ISSUE THREAD

**Issue by ConnorMarble** [graphql-nexus/nexus#949]
So I thought I had Nexus JS figured out, but then I started adding foreign keys and relationships into my postgres database. Nothing complex, or so I thought. All of a sudden, all of my resolvers are throwing errors. I am using prisma but I am staying away from their plugin since it is still in development.

Does anyone have an example project for me to look at? Nexus' examples aren't the best IMO.

Thanks!

-----------------------------------------------

The Error:

" The expected type comes from property 'resolve' which is declared here on type 'NexusOutputFieldConfig<"Author", "books">' "

-------------------------------------------------

My New Database Prisma Schema With Relationship:

```
model author {
id BigInt u/id u/default(autoincrement())
name String
age Int
gender String
book book[]
}
model book {
id BigInt id default(autoincrement())
title String
genre String
author_id BigInt
author author relation(fields: [author_id], references: [id])
}
```
------------------------------------------------

My Nexus Object Types:

```
export const Author = objectType({
name: "Author",
definition(t) {
t.nonNull.int("id");
t.nonNull.int("age");
t.nonNull.string("name");
t.nonNull.string("gender");
t.list.field("books", {
type: Book,
    });
  },
});

export const Book = objectType({
name: "Book",
definition(t) {
t.string("title");
t.string("genre"),
t.int("id"),
t.int("author_id"),
t.field("author", {
type: Author,
      });
  },
});
```

**Comment by ahmedosama7450** [comment]
You need to define custom resolvers for `books` field on `Author` type and for `author` field on `Book` type

Inside of these custom resolvers, you will always use prisma `findUnique`  to automatically batch all the queries (You can't use `findMany` because It's not yet batched by prisma data loader, [look here](https://www.prisma.io/docs/guides/performance-and-optimization/query-optimization-performance#do-i-have-to-use-the-fluent-api-to-enable-batching-of-queries)).

Look at the code in these [examples](https://nexusjs.org/docs/plugins/prisma/removing-the-nexus-plugin-prisma#relation-fields)
